openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0

components:
  schemas:
    OperationEvent:
      type: object
      required: [ event-id, card-id, status, chain-id, amount, currency, transaction-date-time ]
      properties:
        event-id: { type: string, format: uuid }
        card-id: { type: string, format: uuid }
        chain-id: { type: string, format: uuid }
        amount: { type: string, format: decimal }
        currency: { type: string }
        status: { type: string, enum: [ APPROVED, REJECTED, IN_PROGRESS ] }
        transaction-date-time: { type: string, format: date-time }

paths: { }
